fix: missing ws types
This caused the following error:

    ../node_modules/.pnpm/@tui-sandbox+library@2.0.0_typescript@5.6.2/node_modules/@tui-sandbox/library/src/server/connection/trpc.ts:4:32 - error TS7016: Could not find a declaration file for module 'ws'. '/Users/mikavilpas/git/yazi.nvim/node_modules/.pnpm/ws@8.18.0/node_modules/ws/wrapper.mjs' implicitly has an 'any' type.
      Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

    4 import type { WebSocket } from "ws"
                                    ~~~~